Add llama370b_instruct_v1
AAlvAAro/ruby-amazon-bedrock pull request #4
Opened 2024-04-26 16:44 UTC by ErebusBat

Adds Llama 3 Instruct model

https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-meta.html#model-parameters-meta-request-response

This PR bumps the version by two as it build on my other PR #3

2024-04-29 17:28 UTC, AAlvAAro commented
Hi @ErebusBat looks like you'll have to fix conflicts for this PR. Also would you mind trying to add base64 so this issue can be closed and we can link to the PRs. Thanks a lot!

2024-05-15 21:13 UTC, ErebusBat commented
I will rebase to fix conflicts, and look into #5.

2024-05-18 08:10 UTC, AAlvAAro commented on lib/amazon_bedrock/version.rb
> +  VERSION = "0.2.5"
Let's keep it to 0.2.4 version

2024-05-18 08:13 UTC, AAlvAAro requested changes
Hi @ErebusBat thanks for the PR, I left a few comments and please make sure `rspec` and `rubocop` pass. Thanks!

2024-05-18 08:13 UTC, AAlvAAro commented on CHANGELOG.md
> +- Support the use of AWS Named Profiles for authentication
Hi @ErebusBat let's add all your changes to the same version, please add the following notes to the CHANGELOG 

- Support for llama370b_instruct_v1
- Explicitly add base64 gem to dependencies

2024-05-18 08:13 UTC, AAlvAAro commented on README.md
> +You can also use [AWS Named Profiles](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-format-profile) by passing the `profile` keywoard argument. When us
Don't remove the With Configuration documentation, you can add the AWS Named Profiles note below that.

2024-05-18 08:13 UTC, AAlvAAro commented on spec/bedrock_runtime/client_spec.rb
> +      profile: ENV.fetch('AWS_PROFILE', nil)
Please add a new test scenario where the client instantiation is done without the `profile` so both cases are covered.

2024-08-29 16:06 UTC, ErebusBat reviewed
@AAlvAAro My apologies for the delay on addressing these issues.

It looks like some issues on this PR should have been addressed on #3... See comments.

I did update `.env.sample` so that once people copy it to `.env` they can just run the existing specs as I had some issues getting it up and running.

Both `rspec` and `rubocop` are passing on my machine now

2024-09-03 05:36 UTC, AAlvAAro approved these changes

2024-09-03 05:37 UTC, merged